version: "3.8"

services:
  openvpn:
    image: kylemanna/openvpn
    container_name: openvpn
    cap_add:
      - NET_ADMIN
    ports:
      - "443:1194/tcp"
    volumes:
      - ./openvpn:/etc/openvpn
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pgrep", "openvpn"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  asterisk:
    image: mlan/asterisk:base
    container_name: asterisk
    depends_on:
      openvpn:
        condition: service_healthy
    network_mode: "service:openvpn"
    volumes:
      - ./asterisk:/etc/asterisk
    restart: unless-stopped